# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import devicetocentral_pb2 as devicetocentral__pb2


class DeviceToCentralStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterToCentral = channel.unary_unary(
                '/DeviceToCentral/RegisterToCentral',
                request_serializer=devicetocentral__pb2.DeviceInfo.SerializeToString,
                response_deserializer=devicetocentral__pb2.RegStatus.FromString,
                )
        self.HeartBeat = channel.unary_unary(
                '/DeviceToCentral/HeartBeat',
                request_serializer=devicetocentral__pb2.Ping.SerializeToString,
                response_deserializer=devicetocentral__pb2.Pong.FromString,
                )
        self.SendSummary = channel.unary_unary(
                '/DeviceToCentral/SendSummary',
                request_serializer=devicetocentral__pb2.DeviceSummary.SerializeToString,
                response_deserializer=devicetocentral__pb2.SummaryAck.FromString,
                )


class DeviceToCentralServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterToCentral(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartBeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceToCentralServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterToCentral': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterToCentral,
                    request_deserializer=devicetocentral__pb2.DeviceInfo.FromString,
                    response_serializer=devicetocentral__pb2.RegStatus.SerializeToString,
            ),
            'HeartBeat': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartBeat,
                    request_deserializer=devicetocentral__pb2.Ping.FromString,
                    response_serializer=devicetocentral__pb2.Pong.SerializeToString,
            ),
            'SendSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSummary,
                    request_deserializer=devicetocentral__pb2.DeviceSummary.FromString,
                    response_serializer=devicetocentral__pb2.SummaryAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DeviceToCentral', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeviceToCentral(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterToCentral(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DeviceToCentral/RegisterToCentral',
            devicetocentral__pb2.DeviceInfo.SerializeToString,
            devicetocentral__pb2.RegStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HeartBeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DeviceToCentral/HeartBeat',
            devicetocentral__pb2.Ping.SerializeToString,
            devicetocentral__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DeviceToCentral/SendSummary',
            devicetocentral__pb2.DeviceSummary.SerializeToString,
            devicetocentral__pb2.SummaryAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
